// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhMhtf7csBxcVd_L9emTHvRhx4Rrxfwcc',
    appId: '1:795589723045:web:66b9b415ae2a02d8d19e4c',
    messagingSenderId: '795589723045',
    projectId: 'pu-resources-4e5cb',
    authDomain: 'pu-resources-4e5cb.firebaseapp.com',
    storageBucket: 'pu-resources-4e5cb.appspot.com',
    measurementId: 'G-N0DEVEBYNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChBSDUH4rnPRX-dya9ePD85Pk02BD5Rg8',
    appId: '1:795589723045:android:fef6c5802442eaded19e4c',
    messagingSenderId: '795589723045',
    projectId: 'pu-resources-4e5cb',
    storageBucket: 'pu-resources-4e5cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLiRYIndFzThdphItczUYV0u1X7GAF5_k',
    appId: '1:795589723045:ios:6b42950706ca984bd19e4c',
    messagingSenderId: '795589723045',
    projectId: 'pu-resources-4e5cb',
    storageBucket: 'pu-resources-4e5cb.appspot.com',
    iosClientId: '795589723045-rmsdmuunohnnsr0rrbqmmbaop5ed4a47.apps.googleusercontent.com',
    iosBundleId: 'com.example.puResourcse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLiRYIndFzThdphItczUYV0u1X7GAF5_k',
    appId: '1:795589723045:ios:6b42950706ca984bd19e4c',
    messagingSenderId: '795589723045',
    projectId: 'pu-resources-4e5cb',
    storageBucket: 'pu-resources-4e5cb.appspot.com',
    iosClientId: '795589723045-rmsdmuunohnnsr0rrbqmmbaop5ed4a47.apps.googleusercontent.com',
    iosBundleId: 'com.example.puResourcse',
  );
}
